name: climPOSHALLOW
channels:
  - conda-forge
dependencies:
  - python=3.8
  - matplotlib
  - numpy
  - seaborn
  - xarray
  - pandas
  - cartopy
  - cartopy_offlinedata
  - dask
  - scikit-learn
  - scipy
  - netCDF4
  - ipykernel
  